import { Product } from "./types";

export const PRODUCTS: Product[] = [
  {
    id: "1",
    name: "Nike Air Max Dn",
    category: "Men's Shoes",
    price: 160,
    image: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&q=80&w=1000",
    description: "The next generation of Air technology is here. The Air Max Dn features our Dynamic Air unit system of dual-pressure tubes, creating a reactive sensation with every step.",
    colors: ["Black/White", "Volt/Black", "Royal Blue"],
    sizes: ["7", "8", "9", "10", "11", "12"],
    isNew: true,
    isFeatured: true,
  },
  {
    id: "2",
    name: "Nike Dunk Low Retro",
    category: "Men's Shoes",
    price: 115,
    image: "https://images.unsplash.com/photo-1600185365483-26d7a4cc7519?auto=format&fit=crop&q=80&w=1000",
    description: "Created for the hardwood but taken to the streets, the Nike Dunk Low Retro returns with crisp overlays and original team colors.",
    colors: ["Panda", "UNC Blue", "Michigan State"],
    sizes: ["6", "7", "8", "9", "10", "11", "12"],
    isFeatured: true,
  },
  {
    id: "3",
    name: "Nike Air Jordan 1 High OG",
    category: "Men's Shoes",
    price: 180,
    image: "https://images.unsplash.com/photo-1552346154-21d32810aba3?auto=format&fit=crop&q=80&w=1000",
    description: "The Air Jordan 1 Retro High OG is a high-top version of the first signature shoe of Michael Jordan.",
    colors: ["Chicago", "Bred", "Royal"],
    sizes: ["8", "9", "10", "11", "12", "13"],
    isNew: true,
    isFeatured: true,
  },
  {
    id: "4",
    name: "Nike Air Force 1 '07",
    category: "Men's Shoes",
    price: 115,
    image: "https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?auto=format&fit=crop&q=80&w=1000",
    description: "The radiance lives on in the Nike Air Force 1 '07, the b-ball icon that puts a fresh spin on what you know best.",
    colors: ["White/White", "Black/Black"],
    sizes: ["7", "8", "9", "10", "11", "12"],
  },
  {
    id: "5",
    name: "Nike Zoom Vomero 5",
    category: "Men's Shoes",
    price: 160,
    image: "https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?auto=format&fit=crop&q=80&w=1000",
    description: "Carve a new lane for yourself in the Zoom Vomero 5—your go-to for complexity, depth and now, easy styling.",
    colors: ["Photon Dust", "Black", "Oatmeal"],
    sizes: ["7", "8", "9", "10", "11", "12"],
    isNew: true,
  },
  {
    id: "6",
    name: "Nike Pegasus 40",
    category: "Men's Running Shoes",
    price: 130,
    image: "https://images.unsplash.com/photo-1543508282-6319a3e2621f?auto=format&fit=crop&q=80&w=1000",
    description: "A springy ride for every run, the Peg's familiar, just-for-you feel returns to help you accomplish your goals.",
    colors: ["White", "Black", "Blue"],
    sizes: ["7", "8", "9", "10", "11", "12"],
  }
];
